# Generated by Django 3.1.7 on 2021-05-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('adress', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_sms', models.BooleanField(default=False)),
                ('receive_call', models.BooleanField(default=False)),
                ('receive_email', models.BooleanField(default=True)),
                ('receive_app_notification', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'qualifications',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contact')),
                ('notification_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.notificationsettings')),
            ],
            options={
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contact')),
                ('notification_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.notificationsettings')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
