# Generated by Django 3.1.7 on 2021-05-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('info', models.CharField(max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.client')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='protection.task')),
            ],
            options={
                'db_table': 'workflows',
            },
        ),
    ]
